apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: news-reader-Ingress
  namespace: jenkins
  annotations:
    # Nginx Ingress Controllerë¥¼ ì“´ë‹¤ê³  ëª…ì‹œ
    kubernetes.io/ingress.class: nginx
    # (ì„ íƒ) ì ‘ì† ë¡œê·¸ì— ì‹¤ì œ IPê°€ ì°íˆê²Œ í•˜ë ¤ë©´ í•„ìš”í•  ìˆ˜ ìˆìŒ
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: news-reader-api-service # ğŸ‘ˆ ì•„ê¹Œ kubectl get svcë¡œ ë³¸ ê·¸ ì´ë¦„!
            port:
              number: 80                  # ğŸ‘ˆ ì„œë¹„ìŠ¤ì˜ ë‚´ë¶€ í¬íŠ¸ (30265 ì•„ë‹˜!)