apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: news-reader-ingress
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: api.danyeon.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: news-reader-api-service
            port:
              number: 80